import type { LevelCurriculum } from "@/lib/curriculum";

// JLPT N2 — 57 leçons de grammaire · 17 de conjugaison · 70 de vocabulaire.
export const N2: LevelCurriculum = {
  grammar: [
    { code: "N2-01", title: "Les deux constructions en 上で", count: 2 },
    { code: "N2-02", title: "Occasions et préparatifs formels", count: 3 },
    { code: "N2-03", title: "Profiter d'une occasion avec ついでに", count: 1 },
    { code: "N2-04", title: "Succession presque immédiate avec かと思うと", count: 1 },
    { code: "N2-05", title: "Aboutissement après un processus : 末 et あげく", count: 2 },
    { code: "N2-06", title: "Étendue temporelle avec にわたって", count: 1 },
    { code: "N2-07", title: "Point de départ décisif : きっかけ et 契機", count: 1 },
    { code: "N2-08", title: "Résultat dépendant d'un facteur avec 次第", count: 1 },
    { code: "N2-09", title: "Évolution associée avec に伴って", count: 1 },
    { code: "N2-10", title: "Cadre et thème formels : において et に関して", count: 2 },
    { code: "N2-11", title: "Réponse, fondement et conformité : に応じて, に基づいて et に沿って", count: 3 },
    { code: "N2-12", title: "Addition et implication : に加えて et にかかわる", count: 2 },
    { code: "N2-13", title: "Sous une autorité ou un principe avec のもと", count: 1 },
    { code: "N2-14", title: "À travers ou par l'intermédiaire de : 通じて et 通して", count: 2 },
    { code: "N2-15", title: "Autour d'un sujet avec をめぐって", count: 1 },
    { code: "N2-16", title: "Sans distinction avec を問わず", count: 1 },
    { code: "N2-17", title: "À partir d'un modèle avec をもとに", count: 1 },
    { code: "N2-18", title: "Mettre un sentiment dans une action avec をこめて", count: 1 },
    { code: "N2-19", title: "Les trois familles de point de vue en から", count: 3 },
    { code: "N2-20", title: "Seulement et non seulement : のみ, のみならず et ばかりか", count: 3 },
    { code: "N2-21", title: "La cause particulière avec ばかりに", count: 1 },
    { code: "N2-22", title: "La famille だけ : justification, valeur et réputation", count: 4 },
    { code: "N2-23", title: "Minimum acceptable et quantité maximale avec だけ", count: 2 },
    { code: "N2-24", title: "Réduction et identification : にすぎない, でしかない et にほかならない", count: 3 },
    { code: "N2-25", title: "La famille に限る／に限り／に限って／に限らず", count: 4 },
    { code: "N2-26", title: "Les constructions conditionnelles en 限り", count: 4 },
    { code: "N2-27", title: "L'impossibilité situationnelle avec どころではない", count: 1 },
    { code: "N2-28", title: "L'unique option avec しかない et よりほかない", count: 2 },
    { code: "N2-29", title: "Les raisonnements en から : からこそ, からして et からといって", count: 3 },
    { code: "N2-30", title: "Cause supposée ou liée à une personne : のことだから et せいか", count: 2 },
    { code: "N2-31", title: "Cause excessive avec あまり et あまりの", count: 2 },
    { code: "N2-32", title: "Les deux valeurs de 以上", count: 2 },
    { code: "N2-33", title: "La cause formelle avec につき", count: 1 },
    { code: "N2-34", title: "Concession soutenue : ものの, ながらも et にもかかわらず", count: 3 },
    { code: "N2-35", title: "Indépendance avec にかかわらず", count: 1 },
    { code: "N2-36", title: "Évaluation inattendue avec にしては et にしても", count: 2 },
    { code: "N2-37", title: "Concession et conséquence non nécessaire", count: 2 },
    { code: "N2-38", title: "Énumérations ouvertes avec とか et やら", count: 2 },
    { code: "N2-39", title: "Reformuler avec というより", count: 1 },
    { code: "N2-40", title: "Choix imprécis avec か何か et 何かしら", count: 2 },
    { code: "N2-41", title: "La valeur familière de だって", count: 1 },
    { code: "N2-42", title: "Quoi qu'il en soit avec いずれにしても", count: 1 },
    { code: "N2-43", title: "Alternatives concédées avec にせよ et にしろ", count: 2 },
    { code: "N2-44", title: "Nuancer une généralisation avec というものではない", count: 1 },
    { code: "N2-45", title: "Certitude et impression remarquable", count: 2 },
    { code: "N2-46", title: "Valeur d'un effort avec 甲斐", count: 1 },
    { code: "N2-47", title: "Le rejet rhétorique avec ものか", count: 1 },
    { code: "N2-48", title: "Hypothèse difficile et conséquence négative", count: 4 },
    { code: "N2-49", title: "Agir sans accomplir une action avec ことなく", count: 1 },
    { code: "N2-50", title: "La réaction affective avec ことに", count: 1 },
    { code: "N2-51", title: "Possibilité et tendance avec 可能性 et 傾向", count: 2 },
    { code: "N2-52", title: "Norme et comportement avec ものだ et ものではない", count: 2 },
    { code: "N2-53", title: "Les trois constructions grammaticales en 上", count: 3 },
    { code: "N2-54", title: "Ajouter un second statut avec でもある", count: 1 },
    { code: "N2-55", title: "Absence de relation et différence : とは関係なく／とは異なり", count: 2 },
    { code: "N2-56", title: "Manière et ressemblance hypothétique : ふう et かのよう", count: 2 },
    { code: "N2-57", title: "L'apparence perceptible avec ～げ", count: 1 },
  ],
  conjugation: [
    { code: "F1-N2-01", title: "Employer la négation en ん", count: 1 },
    { code: "F1-N2-02", title: "Employer la négation attributive en ぬ", count: 1 },
    { code: "F2-N2-01", title: "Exprimer la simultanéité et l'évolution avec つつ", count: 2 },
    { code: "F2-N2-02", title: "Employer かねる et かねない", count: 2 },
    { code: "F2-N2-03", title: "Employer 得る et 得ない", count: 2 },
    { code: "F2-N2-04", title: "Distinguer づらい et がたい", count: 2 },
    { code: "F2-N2-05", title: "Former l'impossibilité familière en っこない", count: 1 },
    { code: "F2-N2-06", title: "Aller jusqu'au bout avec 抜く et 通す", count: 2 },
    { code: "F2-N2-07", title: "Exprimer la fraîcheur ou le maintien d'un état", count: 2 },
    { code: "F2-N2-08", title: "Distinguer 損なう et 損ねる", count: 2 },
    { code: "F3-N2-01", title: "Exprimer qu'une action suffit ou ne peut être évitée", count: 1 },
    { code: "F3-N2-02", title: "Exprimer qu'on ne peut continuer sans agir", count: 2 },
    { code: "F3-N2-03", title: "Accorder une permission sans objection", count: 2 },
    { code: "F3-N2-04", title: "Exprimer qu'une situation est intenable avec かなわない", count: 1 },
    { code: "HC-N2-01", title: "Construire l'auxiliaire まい", count: 3 },
    { code: "HC-N2-02", title: "Construire l'auxiliaire べき", count: 2 },
    { code: "HC-N2-03", title: "Distinguer les valeurs partageant la même forme", count: 1 },
  ],
  vocab: [
    { code: "V-N2-01", title: "Expressions, politesse et communication", count: 29 },
    { code: "V-N2-02", title: "Nombres, compteurs, mesures et quantités — 1/2", count: 22 },
    { code: "V-N2-03", title: "Nombres, compteurs, mesures et quantités — 2/2", count: 21 },
    { code: "V-N2-04", title: "Temps, calendrier et fréquence — 1/2", count: 26 },
    { code: "V-N2-05", title: "Temps, calendrier et fréquence — 2/2", count: 25 },
    { code: "V-N2-06", title: "Personnes, famille et relations", count: 32 },
    { code: "V-N2-07", title: "Corps, santé et soins — 1/2", count: 25 },
    { code: "V-N2-08", title: "Corps, santé et soins — 2/2", count: 24 },
    { code: "V-N2-09", title: "Maison, objets et vie quotidienne — 1/2", count: 25 },
    { code: "V-N2-10", title: "Maison, objets et vie quotidienne — 2/2", count: 24 },
    { code: "V-N2-11", title: "Alimentation, cuisine et restauration", count: 35 },
    { code: "V-N2-12", title: "Vêtements, apparence et couleurs", count: 26 },
    { code: "V-N2-13", title: "École, études et langue — 1/2", count: 30 },
    { code: "V-N2-14", title: "École, études et langue — 2/2", count: 29 },
    { code: "V-N2-15", title: "Travail, commerce, argent et économie — 1/3", count: 25 },
    { code: "V-N2-16", title: "Travail, commerce, argent et économie — 2/3", count: 25 },
    { code: "V-N2-17", title: "Travail, commerce, argent et économie — 3/3", count: 25 },
    { code: "V-N2-18", title: "Lieux, ville et services — 1/2", count: 24 },
    { code: "V-N2-19", title: "Lieux, ville et services — 2/2", count: 23 },
    { code: "V-N2-20", title: "Transport, voyage et orientation — 1/2", count: 24 },
    { code: "V-N2-21", title: "Transport, voyage et orientation — 2/2", count: 23 },
    { code: "V-N2-22", title: "Nature, météo, animaux et plantes — 1/2", count: 22 },
    { code: "V-N2-23", title: "Nature, météo, animaux et plantes — 2/2", count: 22 },
    { code: "V-N2-24", title: "Culture, loisirs et sport", count: 23 },
    { code: "V-N2-25", title: "Société, droit et politique", count: 15 },
    { code: "V-N2-26", title: "Émotions, caractère et vie sociale", count: 16 },
    { code: "V-N2-27", title: "Pensée, perception, raisonnement et abstractions — 1/2", count: 32 },
    { code: "V-N2-28", title: "Pensée, perception, raisonnement et abstractions — 2/2", count: 32 },
    { code: "V-N2-29", title: "Mouvement, position et actions physiques — 1/2", count: 31 },
    { code: "V-N2-30", title: "Mouvement, position et actions physiques — 2/2", count: 31 },
    { code: "V-N2-31", title: "États, changements et propriétés — 1/3", count: 30 },
    { code: "V-N2-32", title: "États, changements et propriétés — 2/3", count: 30 },
    { code: "V-N2-33", title: "États, changements et propriétés — 3/3", count: 30 },
    { code: "V-N2-34", title: "Adverbes, connecteurs, mots-outils et nuances — 1/2", count: 27 },
    { code: "V-N2-35", title: "Adverbes, connecteurs, mots-outils et nuances — 2/2", count: 26 },
    { code: "V-N2-36", title: "Verbes généraux — 1/6", count: 32 },
    { code: "V-N2-37", title: "Verbes généraux — 2/6", count: 32 },
    { code: "V-N2-38", title: "Verbes généraux — 3/6", count: 32 },
    { code: "V-N2-39", title: "Verbes généraux — 4/6", count: 31 },
    { code: "V-N2-40", title: "Verbes généraux — 5/6", count: 31 },
    { code: "V-N2-41", title: "Verbes généraux — 6/6", count: 31 },
    { code: "V-N2-42", title: "Adjectifs et descriptions — 1/6", count: 32 },
    { code: "V-N2-43", title: "Adjectifs et descriptions — 2/6", count: 32 },
    { code: "V-N2-44", title: "Adjectifs et descriptions — 3/6", count: 32 },
    { code: "V-N2-45", title: "Adjectifs et descriptions — 4/6", count: 32 },
    { code: "V-N2-46", title: "Adjectifs et descriptions — 5/6", count: 32 },
    { code: "V-N2-47", title: "Adjectifs et descriptions — 6/6", count: 32 },
    { code: "V-N2-48", title: "Noms et notions générales — 1/23", count: 31 },
    { code: "V-N2-49", title: "Noms et notions générales — 2/23", count: 31 },
    { code: "V-N2-50", title: "Noms et notions générales — 3/23", count: 31 },
    { code: "V-N2-51", title: "Noms et notions générales — 4/23", count: 31 },
    { code: "V-N2-52", title: "Noms et notions générales — 5/23", count: 31 },
    { code: "V-N2-53", title: "Noms et notions générales — 6/23", count: 31 },
    { code: "V-N2-54", title: "Noms et notions générales — 7/23", count: 30 },
    { code: "V-N2-55", title: "Noms et notions générales — 8/23", count: 30 },
    { code: "V-N2-56", title: "Noms et notions générales — 9/23", count: 30 },
    { code: "V-N2-57", title: "Noms et notions générales — 10/23", count: 30 },
    { code: "V-N2-58", title: "Noms et notions générales — 11/23", count: 30 },
    { code: "V-N2-59", title: "Noms et notions générales — 12/23", count: 30 },
    { code: "V-N2-60", title: "Noms et notions générales — 13/23", count: 30 },
    { code: "V-N2-61", title: "Noms et notions générales — 14/23", count: 30 },
    { code: "V-N2-62", title: "Noms et notions générales — 15/23", count: 30 },
    { code: "V-N2-63", title: "Noms et notions générales — 16/23", count: 30 },
    { code: "V-N2-64", title: "Noms et notions générales — 17/23", count: 30 },
    { code: "V-N2-65", title: "Noms et notions générales — 18/23", count: 30 },
    { code: "V-N2-66", title: "Noms et notions générales — 19/23", count: 30 },
    { code: "V-N2-67", title: "Noms et notions générales — 20/23", count: 30 },
    { code: "V-N2-68", title: "Noms et notions générales — 21/23", count: 30 },
    { code: "V-N2-69", title: "Noms et notions générales — 22/23", count: 30 },
    { code: "V-N2-70", title: "Noms et notions générales — 23/23", count: 30 },
  ],
};
