import type { LevelCurriculum } from "@/lib/curriculum";

// JLPT N1 — 74 leçons de grammaire · 11 de conjugaison · 99 de vocabulaire.
export const N1: LevelCurriculum = {
  grammar: [
    { code: "N1-01", title: "Les marqueurs d'immédiateté", count: 4 },
    { code: "N1-02", title: "Surprise ou répétition après une action", count: 2 },
    { code: "N1-03", title: "Activité parallèle et occasion secondaire", count: 2 },
    { code: "N1-04", title: "Étapes, lancement et tournant : 経て, 皮切り et 境", count: 3 },
    { code: "N1-05", title: "Approche et antériorité : 控えて et 先駆けて", count: 2 },
    { code: "N1-06", title: "La famille いかん", count: 2 },
    { code: "N1-07", title: "Condition et circonstance exceptionnelles : とあれば／とあって", count: 2 },
    { code: "N1-08", title: "Alternatives indifférentes avec であれ et であろうと", count: 2 },
    { code: "N1-09", title: "Les alternatives en なり", count: 2 },
    { code: "N1-10", title: "Deux aspects proposés avec といい", count: 1 },
    { code: "N1-11", title: "Rang et changement de degré avec とも", count: 2 },
    { code: "N1-12", title: "Cause exclusive et conséquence ultime en ば", count: 2 },
    { code: "N1-13", title: "La question binaire avec か否か", count: 1 },
    { code: "N1-14", title: "Propriétés parallèles : A も～なら、B も～", count: 1 },
    { code: "N1-15", title: "Alternative adjectivale avec かれ～かれ", count: 1 },
    { code: "N1-16", title: "Quoi qu'il en soit avec いずれにしても", count: 1 },
    { code: "N1-17", title: "Indépendance avec によらず", count: 1 },
    { code: "N1-18", title: "Mettre un cas à part avec はいざ知らず", count: 1 },
    { code: "N1-19", title: "La concession littéraire avec といえども", count: 1 },
    { code: "N1-20", title: "Comparaison et contraste marqués", count: 3 },
    { code: "N1-21", title: "Deux facteurs combinés avec と相まって", count: 1 },
    { code: "N1-22", title: "Ignorer une difficulté ou une opposition", count: 4 },
    { code: "N1-23", title: "Regret, politesse et circonstance avec ところを／ものを", count: 2 },
    { code: "N1-24", title: "Mise en relief d'un minimum : すら, たりとも et だに", count: 3 },
    { code: "N1-25", title: "L'énumération critique avec だの～だの", count: 1 },
    { code: "N1-26", title: "Les concessions mises en relief par こそ", count: 2 },
    { code: "N1-27", title: "Causes soutenues : ゆえ, こととて et こともあって", count: 3 },
    { code: "N1-28", title: "Condition indispensable ou contexte exceptionnel : あっての／にあって", count: 2 },
    { code: "N1-29", title: "Conformité à un fait, une norme ou une règle", count: 3 },
    { code: "N1-30", title: "S'appuyer sur des éléments antérieurs ou une prémisse", count: 2 },
    { code: "N1-31", title: "Prendre une raison comme prétexte avec かこつけて", count: 1 },
    { code: "N1-32", title: "Cumuler deux fonctions avec を兼ねて", count: 1 },
    { code: "N1-33", title: "Moment officiel ou tournant : をもって et を機に", count: 2 },
    { code: "N1-34", title: "La famille に至る", count: 4 },
    { code: "N1-35", title: "Dépendre entièrement de avec にかかっている", count: 1 },
    { code: "N1-36", title: "Contrainte subie ou imposée avec 余儀なく", count: 2 },
    { code: "N1-37", title: "Aboutissements indésirables : 始末 et 羽目", count: 2 },
    { code: "N1-38", title: "Élément irremplaçable ou préférable", count: 2 },
    { code: "N1-39", title: "Absence de nécessité ou de justification", count: 3 },
    { code: "N1-40", title: "Conséquence impossible à éviter avec では済まない", count: 1 },
    { code: "N1-41", title: "Mérite et valeur suffisante : 値する et 足る", count: 3 },
    { code: "N1-42", title: "Supportable ou insupportable avec 堪える", count: 2 },
    { code: "N1-43", title: "Évidence et sentiment irrépressible", count: 2 },
    { code: "N1-44", title: "Absence totale de moyen", count: 3 },
    { code: "N1-45", title: "Nuancer un jugement négatif", count: 2 },
    { code: "N1-46", title: "Effort resté sans résultat avec 甲斐もなく", count: 1 },
    { code: "N1-47", title: "Les expressions du degré extrême", count: 5 },
    { code: "N1-48", title: "Quantité ou valeur importante avec からある／からの", count: 2 },
    { code: "N1-49", title: "Fixer une dernière limite avec を限りに", count: 1 },
    { code: "N1-50", title: "Accumulation homogène : ずくめ et まみれ", count: 2 },
    { code: "N1-51", title: "Quasi-identité et comparaison évaluative", count: 3 },
    { code: "N1-52", title: "Liberté totale avec 放題", count: 1 },
    { code: "N1-53", title: "Ensemble complet et élément emblématique : ぐるみ／きっての", count: 2 },
    { code: "N1-54", title: "Cumuler deux qualités avec でもあり", count: 1 },
    { code: "N1-55", title: "Négation catégorielle avec でも何でもない", count: 1 },
    { code: "N1-56", title: "Addition emphatique : もとより et さることながら", count: 2 },
    { code: "N1-57", title: "Les suffixes d'apparence めく, ぶる et びる", count: 3 },
    { code: "N1-58", title: "La manière observable avec ぶり／っぷり", count: 1 },
    { code: "N1-59", title: "Impression déplacée ou teintée : がましい et じみる", count: 2 },
    { code: "N1-60", title: "La comparaison littéraire avec ごとき", count: 1 },
    { code: "N1-61", title: "Tendance critiquable et attitude apparente", count: 2 },
    { code: "N1-62", title: "Constat et convention avec もの", count: 2 },
    { code: "N1-63", title: "Donner une estimation avec というところだ", count: 1 },
    { code: "N1-64", title: "Ce qui va sans dire : 言うまでもない et 言わずもがな", count: 2 },
    { code: "N1-65", title: "Mettre un cas problématique au premier plan avec ときたら", count: 1 },
    { code: "N1-66", title: "Surprise et identification rhétorique", count: 2 },
    { code: "N1-67", title: "Les jugements rhétoriques en あるまい et だろうに", count: 3 },
    { code: "N1-68", title: "Hésitation entre deux caractérisations avec というか", count: 1 },
    { code: "N1-69", title: "Valeur unique ou stade exceptionnel : ならでは et にして", count: 2 },
    { code: "N1-70", title: "Mise en relief minimale avec たりとも", count: 1 },
    { code: "N1-71", title: "Les prescriptions littéraires en べく", count: 3 },
    { code: "N1-72", title: "Le jugement d'inadmissibilité avec まじき", count: 1 },
    { code: "N1-73", title: "Absence préalable avec なしに et こととなしに", count: 2 },
    { code: "N1-74", title: "Prévenir absolument une occurrence avec ことのないように", count: 1 },
  ],
  conjugation: [
    { code: "F1-N1-01", title: "Reconnaître les formes littéraires de la négation", count: 4 },
    { code: "F2-N1-01", title: "Exprimer une occasion manquée ou une action bloquée", count: 2 },
    { code: "F2-N1-02", title: "Répéter massivement ou exécuter avec maîtrise", count: 2 },
    { code: "F2-N1-03", title: "Reconnaître l'auxiliaire méprisant やがる", count: 1 },
    { code: "F2-N1-04", title: "Mener une action à bonne fin avec おおせる", count: 1 },
    { code: "F3-N1-01", title: "Exprimer une continuité ou une conséquence inévitable", count: 2 },
    { code: "F3-N1-02", title: "Dire qu'une situation ne peut rester sans réparation", count: 1 },
    { code: "F3-N1-03", title: "Employer てはばからない", count: 1 },
    { code: "HC-N1-01", title: "Reconnaître les principales formes de べし", count: 4 },
    { code: "HC-N1-02", title: "Reconnaître les formes de l'impossibilité ou de l'interdiction", count: 2 },
    { code: "HC-N1-03", title: "Reconnaître le ん volitif ou conjectural", count: 1 },
  ],
  vocab: [
    { code: "V-N1-01", title: "Expressions, politesse et communication — 1/2", count: 23 },
    { code: "V-N1-02", title: "Expressions, politesse et communication — 2/2", count: 23 },
    { code: "V-N1-03", title: "Nombres, compteurs, mesures et quantités", count: 24 },
    { code: "V-N1-04", title: "Temps, calendrier et fréquence", count: 34 },
    { code: "V-N1-05", title: "Personnes, famille et relations — 1/2", count: 25 },
    { code: "V-N1-06", title: "Personnes, famille et relations — 2/2", count: 25 },
    { code: "V-N1-07", title: "Corps, santé et soins — 1/3", count: 26 },
    { code: "V-N1-08", title: "Corps, santé et soins — 2/3", count: 26 },
    { code: "V-N1-09", title: "Corps, santé et soins — 3/3", count: 25 },
    { code: "V-N1-10", title: "Maison, objets et vie quotidienne", count: 30 },
    { code: "V-N1-11", title: "Alimentation, cuisine et restauration", count: 27 },
    { code: "V-N1-12", title: "Vêtements, apparence et couleurs", count: 16 },
    { code: "V-N1-13", title: "École, études et langue — 1/2", count: 35 },
    { code: "V-N1-14", title: "École, études et langue — 2/2", count: 35 },
    { code: "V-N1-15", title: "Travail, commerce, argent et économie — 1/4", count: 30 },
    { code: "V-N1-16", title: "Travail, commerce, argent et économie — 2/4", count: 30 },
    { code: "V-N1-17", title: "Travail, commerce, argent et économie — 3/4", count: 30 },
    { code: "V-N1-18", title: "Travail, commerce, argent et économie — 4/4", count: 30 },
    { code: "V-N1-19", title: "Lieux, ville et services — 1/2", count: 25 },
    { code: "V-N1-20", title: "Lieux, ville et services — 2/2", count: 24 },
    { code: "V-N1-21", title: "Transport, voyage et orientation — 1/2", count: 22 },
    { code: "V-N1-22", title: "Transport, voyage et orientation — 2/2", count: 21 },
    { code: "V-N1-23", title: "Nature, météo, animaux et plantes — 1/2", count: 31 },
    { code: "V-N1-24", title: "Nature, météo, animaux et plantes — 2/2", count: 30 },
    { code: "V-N1-25", title: "Culture, loisirs et sport", count: 19 },
    { code: "V-N1-26", title: "Société, droit et politique", count: 36 },
    { code: "V-N1-27", title: "Émotions, caractère et vie sociale — 1/2", count: 28 },
    { code: "V-N1-28", title: "Émotions, caractère et vie sociale — 2/2", count: 27 },
    { code: "V-N1-29", title: "Pensée, perception, raisonnement et abstractions — 1/4", count: 32 },
    { code: "V-N1-30", title: "Pensée, perception, raisonnement et abstractions — 2/4", count: 32 },
    { code: "V-N1-31", title: "Pensée, perception, raisonnement et abstractions — 3/4", count: 32 },
    { code: "V-N1-32", title: "Pensée, perception, raisonnement et abstractions — 4/4", count: 31 },
    { code: "V-N1-33", title: "Mouvement, position et actions physiques — 1/3", count: 26 },
    { code: "V-N1-34", title: "Mouvement, position et actions physiques — 2/3", count: 26 },
    { code: "V-N1-35", title: "Mouvement, position et actions physiques — 3/3", count: 25 },
    { code: "V-N1-36", title: "États, changements et propriétés — 1/4", count: 29 },
    { code: "V-N1-37", title: "États, changements et propriétés — 2/4", count: 29 },
    { code: "V-N1-38", title: "États, changements et propriétés — 3/4", count: 29 },
    { code: "V-N1-39", title: "États, changements et propriétés — 4/4", count: 28 },
    { code: "V-N1-40", title: "Adverbes, connecteurs, mots-outils et nuances — 1/2", count: 25 },
    { code: "V-N1-41", title: "Adverbes, connecteurs, mots-outils et nuances — 2/2", count: 24 },
    { code: "V-N1-42", title: "Verbes généraux — 1/9", count: 30 },
    { code: "V-N1-43", title: "Verbes généraux — 2/9", count: 30 },
    { code: "V-N1-44", title: "Verbes généraux — 3/9", count: 30 },
    { code: "V-N1-45", title: "Verbes généraux — 4/9", count: 30 },
    { code: "V-N1-46", title: "Verbes généraux — 5/9", count: 30 },
    { code: "V-N1-47", title: "Verbes généraux — 6/9", count: 29 },
    { code: "V-N1-48", title: "Verbes généraux — 7/9", count: 29 },
    { code: "V-N1-49", title: "Verbes généraux — 8/9", count: 29 },
    { code: "V-N1-50", title: "Verbes généraux — 9/9", count: 29 },
    { code: "V-N1-51", title: "Adjectifs et descriptions — 1/9", count: 31 },
    { code: "V-N1-52", title: "Adjectifs et descriptions — 2/9", count: 31 },
    { code: "V-N1-53", title: "Adjectifs et descriptions — 3/9", count: 31 },
    { code: "V-N1-54", title: "Adjectifs et descriptions — 4/9", count: 31 },
    { code: "V-N1-55", title: "Adjectifs et descriptions — 5/9", count: 31 },
    { code: "V-N1-56", title: "Adjectifs et descriptions — 6/9", count: 31 },
    { code: "V-N1-57", title: "Adjectifs et descriptions — 7/9", count: 31 },
    { code: "V-N1-58", title: "Adjectifs et descriptions — 8/9", count: 31 },
    { code: "V-N1-59", title: "Adjectifs et descriptions — 9/9", count: 31 },
    { code: "V-N1-60", title: "Noms et notions générales — 1/40", count: 31 },
    { code: "V-N1-61", title: "Noms et notions générales — 2/40", count: 31 },
    { code: "V-N1-62", title: "Noms et notions générales — 3/40", count: 31 },
    { code: "V-N1-63", title: "Noms et notions générales — 4/40", count: 31 },
    { code: "V-N1-64", title: "Noms et notions générales — 5/40", count: 31 },
    { code: "V-N1-65", title: "Noms et notions générales — 6/40", count: 31 },
    { code: "V-N1-66", title: "Noms et notions générales — 7/40", count: 31 },
    { code: "V-N1-67", title: "Noms et notions générales — 8/40", count: 31 },
    { code: "V-N1-68", title: "Noms et notions générales — 9/40", count: 31 },
    { code: "V-N1-69", title: "Noms et notions générales — 10/40", count: 31 },
    { code: "V-N1-70", title: "Noms et notions générales — 11/40", count: 30 },
    { code: "V-N1-71", title: "Noms et notions générales — 12/40", count: 30 },
    { code: "V-N1-72", title: "Noms et notions générales — 13/40", count: 30 },
    { code: "V-N1-73", title: "Noms et notions générales — 14/40", count: 30 },
    { code: "V-N1-74", title: "Noms et notions générales — 15/40", count: 30 },
    { code: "V-N1-75", title: "Noms et notions générales — 16/40", count: 30 },
    { code: "V-N1-76", title: "Noms et notions générales — 17/40", count: 30 },
    { code: "V-N1-77", title: "Noms et notions générales — 18/40", count: 30 },
    { code: "V-N1-78", title: "Noms et notions générales — 19/40", count: 30 },
    { code: "V-N1-79", title: "Noms et notions générales — 20/40", count: 30 },
    { code: "V-N1-80", title: "Noms et notions générales — 21/40", count: 30 },
    { code: "V-N1-81", title: "Noms et notions générales — 22/40", count: 30 },
    { code: "V-N1-82", title: "Noms et notions générales — 23/40", count: 30 },
    { code: "V-N1-83", title: "Noms et notions générales — 24/40", count: 30 },
    { code: "V-N1-84", title: "Noms et notions générales — 25/40", count: 30 },
    { code: "V-N1-85", title: "Noms et notions générales — 26/40", count: 30 },
    { code: "V-N1-86", title: "Noms et notions générales — 27/40", count: 30 },
    { code: "V-N1-87", title: "Noms et notions générales — 28/40", count: 30 },
    { code: "V-N1-88", title: "Noms et notions générales — 29/40", count: 30 },
    { code: "V-N1-89", title: "Noms et notions générales — 30/40", count: 30 },
    { code: "V-N1-90", title: "Noms et notions générales — 31/40", count: 30 },
    { code: "V-N1-91", title: "Noms et notions générales — 32/40", count: 30 },
    { code: "V-N1-92", title: "Noms et notions générales — 33/40", count: 30 },
    { code: "V-N1-93", title: "Noms et notions générales — 34/40", count: 30 },
    { code: "V-N1-94", title: "Noms et notions générales — 35/40", count: 30 },
    { code: "V-N1-95", title: "Noms et notions générales — 36/40", count: 30 },
    { code: "V-N1-96", title: "Noms et notions générales — 37/40", count: 30 },
    { code: "V-N1-97", title: "Noms et notions générales — 38/40", count: 30 },
    { code: "V-N1-98", title: "Noms et notions générales — 39/40", count: 30 },
    { code: "V-N1-99", title: "Noms et notions générales — 40/40", count: 30 },
  ],
};
