import type { LevelCurriculum } from "@/lib/curriculum";

// JLPT N4 — 49 leçons de grammaire · 25 de conjugaison · 28 de vocabulaire.
export const N4: LevelCurriculum = {
  grammar: [
    { code: "N4-01", title: "Nominaliser et reformuler un fait avec こと", count: 2 },
    { code: "N4-02", title: "Nommer et citer avec という et と言う", count: 2 },
    { code: "N4-03", title: "Exprimer une pensée ou une opinion avec と思う", count: 1 },
    { code: "N4-04", title: "Les questions intégrées : ～か et ～かどうか", count: 2 },
    { code: "N4-05", title: "Information rapportée et interprétation conventionnelle", count: 3 },
    { code: "N4-06", title: "Le moment d'une action avec とき", count: 1 },
    { code: "N4-07", title: "La durée avec 間 et 間に", count: 2 },
    { code: "N4-08", title: "Échéance et programme : までに et 予定", count: 2 },
    { code: "N4-09", title: "Condition régulière et cas éventuel : と et 場合", count: 2 },
    { code: "N4-10", title: "La période approximative avec くらい／ぐらい", count: 1 },
    { code: "N4-11", title: "Cause et objectif avec ので et ため", count: 2 },
    { code: "N4-12", title: "Exprimer un but orienté vers un résultat avec ように", count: 1 },
    { code: "N4-13", title: "Concession et opposition avec のに et だが", count: 2 },
    { code: "N4-14", title: "Ajouter plusieurs raisons avec ～し、～し", count: 1 },
    { code: "N4-15", title: "Relier le discours avec それに, それで et それでも", count: 3 },
    { code: "N4-16", title: "Illustration et alternatives avec でも", count: 3 },
    { code: "N4-17", title: "La condition contextuelle avec なら", count: 2 },
    { code: "N4-18", title: "La conséquence automatique avec と", count: 1 },
    { code: "N4-19", title: "Conseil et regret hypothétiques", count: 2 },
    { code: "N4-20", title: "Faible degré et restriction négative : あまり et しか", count: 2 },
    { code: "N4-21", title: "La limitation par un seul moyen avec だけで", count: 1 },
    { code: "N4-22", title: "La répartition régulière avec ずつ", count: 1 },
    { code: "N4-23", title: "Exemplification et prédominance : など et ばかり", count: 2 },
    { code: "N4-24", title: "Bornes quantitatives : 以上 et 以下", count: 2 },
    { code: "N4-25", title: "L'intervalle de A à B avec から et まで", count: 1 },
    { code: "N4-26", title: "Le nombre approximatif avec ほど", count: 1 },
    { code: "N4-27", title: "Sentiment observable et trait de caractère : ～がる et ～がり", count: 2 },
    { code: "N4-28", title: "Ressemblance avec みたい et よう", count: 2 },
    { code: "N4-29", title: "Apparence et déduction avec に見える et と見える", count: 2 },
    { code: "N4-30", title: "Incertitude et question intérieure", count: 3 },
    { code: "N4-31", title: "Le caractère typique avec らしい", count: 1 },
    { code: "N4-32", title: "Le style ou l'aspect avec 風", count: 1 },
    { code: "N4-33", title: "L'occurrence occasionnelle avec ことがある", count: 1 },
    { code: "N4-34", title: "Décision personnelle et décision extérieure", count: 2 },
    { code: "N4-35", title: "Effort volontaire et évolution avec ようにする／なる", count: 2 },
    { code: "N4-36", title: "La capacité périphrastique avec ことができる", count: 1 },
    { code: "N4-37", title: "Nécessité et absence de nécessité", count: 2 },
    { code: "N4-38", title: "Intention immédiate et choix entre plusieurs options", count: 2 },
    { code: "N4-39", title: "La perception sensorielle avec がする", count: 1 },
    { code: "N4-40", title: "Destination, usage prévu et finalité d'un objet", count: 2 },
    { code: "N4-41", title: "Introduire un thème avec について", count: 1 },
    { code: "N4-42", title: "Appartenance à une catégorie ou à un ensemble", count: 2 },
    { code: "N4-43", title: "Politesse renforcée : でございます et préfixes お／ご", count: 2 },
    { code: "N4-44", title: "Atténuer une demande ou un propos avec んですが", count: 1 },
    { code: "N4-45", title: "Combinaisons de particules avec は et の", count: 2 },
    { code: "N4-46", title: "La restriction contrastive avec だけは", count: 1 },
    { code: "N4-47", title: "La mise en relief familière avec って", count: 1 },
    { code: "N4-48", title: "Confirmation, surprise et invitation avec じゃないか", count: 1 },
    { code: "N4-49", title: "La question familière avec かい", count: 1 },
  ],
  conjugation: [
    { code: "F1-N4-01", title: "Construire le passif", count: 3 },
    { code: "F1-N4-02", title: "Construire le causatif", count: 3 },
    { code: "F1-N4-03", title: "Décliner la négation en condition et en contrainte", count: 2 },
    { code: "F2-N4-01", title: "Exprimer le désir d'un tiers avec たがる", count: 2 },
    { code: "F2-N4-02", title: "Exprimer l'excès avec すぎる", count: 2 },
    { code: "F2-N4-03", title: "Commencer, poursuivre et terminer une action", count: 3 },
    { code: "F2-N4-04", title: "Évaluer la facilité d'exécution", count: 2 },
    { code: "F2-N4-05", title: "Former l'apparence immédiate avec そう", count: 2 },
    { code: "F2-N4-06", title: "Donner une consigne et mener deux actions ensemble", count: 2 },
    { code: "F3-N4-01", title: "Essayer, préparer et achever une action", count: 3 },
    { code: "F3-N4-02", title: "Exprimer un état résultant intentionnel avec ある", count: 1 },
    { code: "F3-N4-03", title: "Distinguer ていく et てくる", count: 2 },
    { code: "F3-N4-04", title: "Construire le système donner–recevoir après une action", count: 3 },
    { code: "F3-N4-05", title: "Employer てほしい et てほしがる", count: 2 },
    { code: "F3-N4-06", title: "Nuancer la relation sociale avec les auxiliaires de don", count: 3 },
    { code: "F3-N4-07", title: "Reconnaître les contractions des auxiliaires fréquents", count: 3 },
    { code: "F3-N4-08", title: "Inviter à essayer ou promettre de montrer", count: 2 },
    { code: "F3-N4-09", title: "Exprimer la répétition ou l'impossibilité de rester dans un état", count: 2 },
    { code: "F3-N4-10", title: "Élever le degré de politesse d'une demande", count: 2 },
    { code: "F3-N4-11", title: "Former l'interdiction familière", count: 1 },
    { code: "HC-N4-01", title: "Construire la capacité selon le groupe", count: 4 },
    { code: "HC-N4-02", title: "Construire la volonté ou la proposition neutre", count: 3 },
    { code: "HC-N4-03", title: "Construire le conditionnel morphologique", count: 3 },
    { code: "HC-N4-04", title: "Construire l'ordre direct et l'interdiction", count: 4 },
    { code: "HC-N4-05", title: "Former la condition en たら et l'alternative en たり", count: 2 },
  ],
  vocab: [
    { code: "V-N4-01", title: "Expressions, politesse et communication", count: 20 },
    { code: "V-N4-02", title: "Nombres, temps, calendrier et fréquence", count: 19 },
    { code: "V-N4-03", title: "Personnes, famille et relations", count: 17 },
    { code: "V-N4-04", title: "Corps, santé et soins", count: 17 },
    { code: "V-N4-05", title: "Maison, objets, vêtements et apparence", count: 21 },
    { code: "V-N4-06", title: "Alimentation, cuisine et restauration", count: 17 },
    { code: "V-N4-07", title: "École, études et langue", count: 15 },
    { code: "V-N4-08", title: "Travail, commerce, argent et économie", count: 18 },
    { code: "V-N4-09", title: "Lieux, ville et services", count: 17 },
    { code: "V-N4-10", title: "Transport, voyage et orientation", count: 19 },
    { code: "V-N4-11", title: "Nature, météo, animaux et plantes", count: 18 },
    { code: "V-N4-12", title: "Culture, société et vie sociale", count: 32 },
    { code: "V-N4-13", title: "Pensée, perception, raisonnement et abstractions", count: 27 },
    { code: "V-N4-14", title: "Mouvement, position et actions physiques", count: 25 },
    { code: "V-N4-15", title: "États, changements et propriétés — 1/2", count: 22 },
    { code: "V-N4-16", title: "États, changements et propriétés — 2/2", count: 21 },
    { code: "V-N4-17", title: "Adverbes, connecteurs, mots-outils et nuances — 1/2", count: 20 },
    { code: "V-N4-18", title: "Adverbes, connecteurs, mots-outils et nuances — 2/2", count: 20 },
    { code: "V-N4-19", title: "Verbes généraux — 1/2", count: 33 },
    { code: "V-N4-20", title: "Verbes généraux — 2/2", count: 33 },
    { code: "V-N4-21", title: "Adjectifs et descriptions — 1/2", count: 34 },
    { code: "V-N4-22", title: "Adjectifs et descriptions — 2/2", count: 33 },
    { code: "V-N4-23", title: "Noms et notions générales — 1/6", count: 30 },
    { code: "V-N4-24", title: "Noms et notions générales — 2/6", count: 30 },
    { code: "V-N4-25", title: "Noms et notions générales — 3/6", count: 29 },
    { code: "V-N4-26", title: "Noms et notions générales — 4/6", count: 29 },
    { code: "V-N4-27", title: "Noms et notions générales — 5/6", count: 29 },
    { code: "V-N4-28", title: "Noms et notions générales — 6/6", count: 29 },
  ],
};
