import type { LevelCurriculum } from "@/lib/curriculum";

// JLPT N3 — 56 leçons de grammaire · 13 de conjugaison · 60 de vocabulaire.
export const N3: LevelCurriculum = {
  grammar: [
    { code: "N3-01", title: "Pendant qu'une situation subsiste : うちに et ないうちに", count: 2 },
    { code: "N3-02", title: "Action en cours : 最中 et 途中", count: 2 },
    { code: "N3-03", title: "Répétition régulière : たびに et ごとに", count: 2 },
    { code: "N3-04", title: "Les constructions temporelles en ところ", count: 3 },
    { code: "N3-05", title: "Tentative ou action sur le point de commencer avec 意向形 + とする", count: 1 },
    { code: "N3-06", title: "Repère ponctuel ou point de départ : 以来 et 際", count: 2 },
    { code: "N3-07", title: "Évolutions parallèles : につれて, にしたがって et とともに", count: 3 },
    { code: "N3-08", title: "Construire et concéder une hypothèse avec とする", count: 3 },
    { code: "N3-09", title: "Hypothèse contextuelle avec もしも, なら et 場合", count: 3 },
    { code: "N3-10", title: "Souhait et conseil : といい et ばいい", count: 2 },
    { code: "N3-11", title: "Quel que soit le degré avec どんなに／いくら～ても", count: 1 },
    { code: "N3-12", title: "Conséquence assumée avec からには", count: 1 },
    { code: "N3-13", title: "Résultat favorable ou défavorable : おかげ et せい", count: 2 },
    { code: "N3-14", title: "Exprimer et justifier une cause", count: 3 },
    { code: "N3-15", title: "Cause, moyen et variation avec によって", count: 2 },
    { code: "N3-16", title: "Résultat logique et enchaînement : わけだ et すると", count: 2 },
    { code: "N3-17", title: "ところが et ところで : opposition ou changement de sujet", count: 2 },
    { code: "N3-18", title: "Concession critique ou inattendue : くせに, わりに et のに", count: 3 },
    { code: "N3-19", title: "Deux faces d'une évolution : 一方, 一方だ et 反面", count: 3 },
    { code: "N3-20", title: "Contradiction forte : に反して et どころか", count: 2 },
    { code: "N3-21", title: "Concession partielle avec ～ことは～が", count: 1 },
    { code: "N3-22", title: "Le degré avec ほど et くらい／ぐらい", count: 4 },
    { code: "N3-23", title: "Particules emphatiques : こそ, さえ et まで", count: 3 },
    { code: "N3-24", title: "Restriction et addition : きり, だけしか, だけでなく et しかも", count: 4 },
    { code: "N3-25", title: "Exemple, surprise ou atténuation : なんか, なんて et など", count: 2 },
    { code: "N3-26", title: "Groupes et accumulation : 同士 et だらけ", count: 2 },
    { code: "N3-27", title: "Opposer deux catégories avec 前者 et 後者", count: 1 },
    { code: "N3-28", title: "Devoir, recommandation et absence de nécessité", count: 4 },
    { code: "N3-29", title: "Attente et impossibilité avec はず", count: 2 },
    { code: "N3-30", title: "Les jugements en わけ", count: 3 },
    { code: "N3-31", title: "Certitude et risque : に違いない et おそれがある", count: 2 },
    { code: "N3-32", title: "Propriété générale et intensité affective : ものだ et ことか", count: 2 },
    { code: "N3-33", title: "La négation catégorique avec 決して～ない", count: 1 },
    { code: "N3-34", title: "Rapporter une information : そうだ, らしい, によると et ということだ", count: 4 },
    { code: "N3-35", title: "Exprimer un point de vue avec にとって", count: 1 },
    { code: "N3-36", title: "Rappel et incrédulité : っけ et まさか", count: 2 },
    { code: "N3-37", title: "Définir ou nommer avec というのは, っていう et とは", count: 3 },
    { code: "N3-38", title: "Introduire un thème ou une catégorie avec という", count: 2 },
    { code: "N3-39", title: "Nuancer une formulation avec といっても", count: 1 },
    { code: "N3-40", title: "Registre formel : である et となる", count: 2 },
    { code: "N3-41", title: "La focalisation clivée avec ～のは X のほうだ", count: 1 },
    { code: "N3-42", title: "Cible et rôle : に対して et として", count: 2 },
    { code: "N3-43", title: "La comparaison explicite avec に比べて", count: 1 },
    { code: "N3-44", title: "Le remplacement avec に代わって", count: 1 },
    { code: "N3-45", title: "Centre et élément représentatif : を中心に et をはじめ", count: 2 },
    { code: "N3-46", title: "L'étendue avec から～にかけて", count: 1 },
    { code: "N3-47", title: "Public, adéquation et format : 向け, 向き et 型", count: 3 },
    { code: "N3-48", title: "Influence déterminante avec によって", count: 1 },
    { code: "N3-49", title: "Règle établie et habitude personnelle", count: 2 },
    { code: "N3-50", title: "Agir avec une intention ou faire semblant", count: 2 },
    { code: "N3-51", title: "Remplacement et contrepartie avec 代わりに", count: 1 },
    { code: "N3-52", title: "Procédé conforme à une manière avec ように", count: 1 },
    { code: "N3-53", title: "Sens et motif explicites avec という", count: 2 },
    { code: "N3-54", title: "Les formes productives du keigo", count: 3 },
    { code: "N3-55", title: "Les verbes honorifiques et humbles", count: 3 },
    { code: "N3-56", title: "Les préfixes honorifiques お et ご", count: 1 },
  ],
  conjugation: [
    { code: "F1-N3-01", title: "Construire le causatif-passif", count: 4 },
    { code: "F1-N3-02", title: "Reconnaître les contractions de la condition négative", count: 2 },
    { code: "F1-N3-03", title: "Employer l'auxiliaire négatif ず", count: 3 },
    { code: "F2-N3-01", title: "Marquer le départ soudain ou la fin volontaire", count: 2 },
    { code: "F2-N3-02", title: "Exprimer une action amorcée ou menée jusqu'au bout", count: 3 },
    { code: "F2-N3-03", title: "Refaire une action ou l'accomplir mutuellement", count: 2 },
    { code: "F2-N3-04", title: "Exprimer l'entrée, la montée et l'achèvement ascendant", count: 3 },
    { code: "F2-N3-05", title: "Marquer l'oubli ou ce qui demeure à faire", count: 2 },
    { code: "F3-N3-01", title: "Employer ておる et てまいる", count: 2 },
    { code: "F3-N3-02", title: "Distinguer les trois auxiliaires d'intensité affective", count: 3 },
    { code: "HC-N3-01", title: "Reconnaître la chute de ら", count: 1 },
    { code: "HC-N3-02", title: "Construire le respect et l'humilité avec la base en I", count: 4 },
    { code: "HC-N3-03", title: "Conjuguer les verbes honorifiques et humbles spéciaux", count: 3 },
  ],
  vocab: [
    { code: "V-N3-01", title: "Expressions, politesse et communication", count: 20 },
    { code: "V-N3-02", title: "Nombres, compteurs, mesures et quantités", count: 21 },
    { code: "V-N3-03", title: "Temps, calendrier et fréquence — 1/2", count: 23 },
    { code: "V-N3-04", title: "Temps, calendrier et fréquence — 2/2", count: 22 },
    { code: "V-N3-05", title: "Personnes, famille et relations — 1/2", count: 22 },
    { code: "V-N3-06", title: "Personnes, famille et relations — 2/2", count: 21 },
    { code: "V-N3-07", title: "Corps, santé et soins — 1/2", count: 26 },
    { code: "V-N3-08", title: "Corps, santé et soins — 2/2", count: 25 },
    { code: "V-N3-09", title: "Maison, objets et vie quotidienne", count: 17 },
    { code: "V-N3-10", title: "Alimentation, cuisine et restauration", count: 17 },
    { code: "V-N3-11", title: "Vêtements, apparence et couleurs", count: 15 },
    { code: "V-N3-12", title: "École, études et langue — 1/2", count: 20 },
    { code: "V-N3-13", title: "École, études et langue — 2/2", count: 19 },
    { code: "V-N3-14", title: "Travail, commerce, argent et économie — 1/3", count: 26 },
    { code: "V-N3-15", title: "Travail, commerce, argent et économie — 2/3", count: 25 },
    { code: "V-N3-16", title: "Travail, commerce, argent et économie — 3/3", count: 25 },
    { code: "V-N3-17", title: "Lieux, ville et services", count: 30 },
    { code: "V-N3-18", title: "Transport, voyage et orientation", count: 31 },
    { code: "V-N3-19", title: "Nature, météo, animaux et plantes — 1/2", count: 20 },
    { code: "V-N3-20", title: "Nature, météo, animaux et plantes — 2/2", count: 19 },
    { code: "V-N3-21", title: "Culture, loisirs et sport", count: 18 },
    { code: "V-N3-22", title: "Société, droit et politique", count: 24 },
    { code: "V-N3-23", title: "Émotions, caractère et vie sociale", count: 35 },
    { code: "V-N3-24", title: "Pensée, perception, raisonnement et abstractions — 1/3", count: 25 },
    { code: "V-N3-25", title: "Pensée, perception, raisonnement et abstractions — 2/3", count: 24 },
    { code: "V-N3-26", title: "Pensée, perception, raisonnement et abstractions — 3/3", count: 24 },
    { code: "V-N3-27", title: "Mouvement, position et actions physiques — 1/2", count: 21 },
    { code: "V-N3-28", title: "Mouvement, position et actions physiques — 2/2", count: 20 },
    { code: "V-N3-29", title: "États, changements et propriétés — 1/2", count: 26 },
    { code: "V-N3-30", title: "États, changements et propriétés — 2/2", count: 26 },
    { code: "V-N3-31", title: "Adverbes, connecteurs, mots-outils et nuances — 1/2", count: 23 },
    { code: "V-N3-32", title: "Adverbes, connecteurs, mots-outils et nuances — 2/2", count: 23 },
    { code: "V-N3-33", title: "Verbes généraux — 1/3", count: 34 },
    { code: "V-N3-34", title: "Verbes généraux — 2/3", count: 34 },
    { code: "V-N3-35", title: "Verbes généraux — 3/3", count: 34 },
    { code: "V-N3-36", title: "Adjectifs et descriptions — 1/5", count: 28 },
    { code: "V-N3-37", title: "Adjectifs et descriptions — 2/5", count: 28 },
    { code: "V-N3-38", title: "Adjectifs et descriptions — 3/5", count: 28 },
    { code: "V-N3-39", title: "Adjectifs et descriptions — 4/5", count: 27 },
    { code: "V-N3-40", title: "Adjectifs et descriptions — 5/5", count: 27 },
    { code: "V-N3-41", title: "Noms et notions générales — 1/20", count: 31 },
    { code: "V-N3-42", title: "Noms et notions générales — 2/20", count: 31 },
    { code: "V-N3-43", title: "Noms et notions générales — 3/20", count: 31 },
    { code: "V-N3-44", title: "Noms et notions générales — 4/20", count: 31 },
    { code: "V-N3-45", title: "Noms et notions générales — 5/20", count: 31 },
    { code: "V-N3-46", title: "Noms et notions générales — 6/20", count: 31 },
    { code: "V-N3-47", title: "Noms et notions générales — 7/20", count: 30 },
    { code: "V-N3-48", title: "Noms et notions générales — 8/20", count: 30 },
    { code: "V-N3-49", title: "Noms et notions générales — 9/20", count: 30 },
    { code: "V-N3-50", title: "Noms et notions générales — 10/20", count: 30 },
    { code: "V-N3-51", title: "Noms et notions générales — 11/20", count: 30 },
    { code: "V-N3-52", title: "Noms et notions générales — 12/20", count: 30 },
    { code: "V-N3-53", title: "Noms et notions générales — 13/20", count: 30 },
    { code: "V-N3-54", title: "Noms et notions générales — 14/20", count: 30 },
    { code: "V-N3-55", title: "Noms et notions générales — 15/20", count: 30 },
    { code: "V-N3-56", title: "Noms et notions générales — 16/20", count: 30 },
    { code: "V-N3-57", title: "Noms et notions générales — 17/20", count: 30 },
    { code: "V-N3-58", title: "Noms et notions générales — 18/20", count: 30 },
    { code: "V-N3-59", title: "Noms et notions générales — 19/20", count: 30 },
    { code: "V-N3-60", title: "Noms et notions générales — 20/20", count: 30 },
  ],
};
